package gui.types;

public enum CommandType
{
	MOVE, WORK, BUILD, ATTACK, RESEARCH, SELL, EXCHANGE,

	TRAIN_WORKER, TRAIN_SCHOLAR, TRAIN_HORSE_MACEMAN, TRAIN_SPEARMAN,

	TRAIN_AXMAN, TRAIN_AGILE_CAVALRY, TRAIN_BOAT;
}
