package gui.types;

public enum InfoType
{
	HEALTH, GOLD, STONE, LUMBER, FOOD, ATTACK_SCORE_THIS_SOLDIER,

	INVENTORY, OCCUPATION, SCORE_TOWARD_CAVALRY,

	SCORE_TOWARD_INFANTRY, DEFENCE_SCORE, ATTACK_SCORE,

	GOLD_MINING_EXPERIENCE, STONE_MINING_EXPERIENCE,

	WOOD_CAMP_EXPERIENCE, FOOD_COLLECTING_EXPERIENCE, BUILDING_EXPERIENCE;
}
