/*
 * Enumeration ObjectType keeps the type of an object, 
 * whether it is FARM, GOLD_MINE, MAIN_BUILDING, MARKET, PORT, STOCKPILE, 
 * STONE_MINE, UNIVERSITY, WOOD_CAMP, BOAT, SCHOLAR, or WORKER
 */

package logic.types;

public enum ObjectType
{
	FARM, GOLD_MINE, MAIN_BUILDING, MARKET, PORT, STOCKPILE, STONE_MINE, UNIVERSITY, WOOD_CAMP, BOAT, SCHOLAR, WORKER, STABLE, BARRACK, AGILE_CAVALRY, SPEARMAN, AXMAN, HORSE_MACEMAN;
}
