/*
 * Enumeration ResearchType keeps the type of a research, 
 * whether it is RESOURCES, AGRICULTURE, MINING, LUMBER_MILL, 
 * RANCHING, IRRIGATION, REFINERY, CARPENTRY, FISHING, ECONOMY, 
 * MICRO_ECONOMY, MACRO_ECONOMY, PARSIMONY, TAX, PROJECT_MANAGEMENT, 
 * MARKET, TEAM_WORK, STRATEGIC_PROJECT_MANAGEMENT, SCIENCE, ALPHABET, 
 * MATHEMATICS, ENGINEERING, SCHOOL, UNIVERSITY,  or CERN
 */

package logic.types;

public enum ResearchType
{
	RESOURCES, AGRICULTURE, MINING, LUMBER_MILL, RANCHING, IRRIGATION, REFINERY, CARPENTRY, FISHING, ECONOMY, MICRO_ECONOMY, MACRO_ECONOMY, PARSIMONY, TAX, PROJECT_MANAGEMENT, MARKET, TEAM_WORK, STRATEGIC_PROJECT_MANAGEMENT, SCIENCE, ALPHABET, MATHEMATICS, ENGINEERING, SCHOOL, UNIVERSITY, CERN, MILITARY, HORSEBACK_RIDING, BASIC_COMBAT, ANIMAL_HUSBANDRY, ADVANCED_ARMORS;
}
